### ISSUE TITLE
Tag click causes 404

### ISSUE THREAD

**Issue by esh1n** [jeffreytse/jekyll-theme-yat#1]
![image](https://user-images.githubusercontent.com/2417718/92947914-4f708280-f461-11ea-8e30-e203b4f2a812.png)
 For example please click on **markdown** tag

**Comment by jeffreytse** [comment]
Hi @esh1n 

Now the issue has been addressed. And it is a relative url issue.

Thanks and regards.

**Comment by jeffreytse** [comment]
Hi @esh1n 

This issue has been fixed and the latest gem version ([v1.5.2](https://rubygems.org/gems/jekyll-theme-yat/versions/1.5.2)) has been released.

👍 Welcome to update to the latest version. Thanks for your good help!

Thanks and regards.
