### ISSUE TITLE
Is there a way to disable the TOC?

### ISSUE THREAD

**Issue by woodenbell** [jeffreytse/jekyll-theme-yat#12]
First of all I'd like to say that this theme is pretty awesome. However, in my posts I'd like to use titles without generating a Table of Contents in the sidebar. Is there a way to disable the automatic TOC generation or disable it for a specific post?

**Comment by jeffreytse** [comment]
Hi @woodenbell 

You can disable the TOC by the metadata as below:

```markdown
---
layout: post
title: My first post
sidebar: []
---
Here is your content. You can use `sidebar` field to configure your sidebar.
This example will disable all sidebar components (the TOC component, etc.)
...
```

🎉  Welcome to give a little STAR for support and future updates.

Thanks and regards

**Comment by woodenbell** [comment]
Hi @jeffreytse, thanks!
