### ISSUE TITLE
[Question] Do I have to show banner for each article?

### ISSUE THREAD

**Issue by Liaorannn** [jeffreytse/jekyll-theme-yat#137]
Hi, I currently use your theme in my personal website and I want to thank you for sharing this great theme.

I have a question on articles writing. Every post on my blog has a banner showing them on the front page, whether I set the banner image or not. If I set the image, it will show the banner, but when I didn't set the banner option in the post, it will still show the blank picture. I am wondering whether I can choose some this articles' banner not to show? How can I do this?

My blogs: there exists a blank picture in the red box.
![image](https://github.com/jeffreytse/jekyll-theme-yat/assets/87054675/0cbcf06b-5490-4b02-a7c2-083a2bb1f153)

What I want to:
![image](https://github.com/jeffreytse/jekyll-theme-yat/assets/87054675/13af30a1-7175-4894-8add-5d94f258c3a6)

Thanks for your help!

**Comment by Liaorannn** [comment]
@jeffreytse hi, can you help me?

**Comment by jeffreytse** [comment]
Hi @Liaorannn, it will show with default thumbnail if you have no banner URL configured in your post.

**Comment by Liaorannn** [comment]
Thx a lot! I've add up the origin default image from the demo to my website. But the outcome is still not what i want. There is still exist the default-image plot shown in the homepage. Can I just show the excerpt and no image banner in the homepage(which is just like the second image shown above)? 

after i add the default image:
![image](https://github.com/jeffreytse/jekyll-theme-yat/assets/87054675/88dbd9dd-9217-49bb-80d1-1b282f08c6fa)
