### ISSUE TITLE
time and date BUG

### ISSUE THREAD

**Issue by jadeduo** [jeffreytse/jekyll-theme-yat#14]
The blog display time is inconsistent with the actual time.

**Comment by jeffreytse** [comment]
Hi @jadeduo 

Could you show more details about this issue?

Thanks and regards

**Comment by jadeduo** [comment]
> Hi @jadeduo
> 
> Could you show more details about this issue?
> 
> Thanks and regards
I think I've solved it. It's my problem. Thank you!
