### ISSUE TITLE
Visitor's choice Light vs Dark is not kept when another page is loaded

### ISSUE THREAD

**Issue by Pixinn** [jeffreytse/jekyll-theme-yat#15]
If the light theme is forced by default using _night_mode: "off"_ and the visitor manually choose "Dark" with the widget, his setting is lost when he goes to another page. The new one is displayed with the light theme.
I think whatever the user's choice is, it should supersede the default setting of the site and be kept during the visit.

**Comment by jeffreytse** [comment]
Hi @Pixinn 

Firstly, thanks for your good suggestion on the dark mode setting. According to your description, I have improved the dark mode to better strategy. The new strategy is as below:

Whatever the user's choice is, it will supersede the default setting of the site and be kept during the visit (__session__). Only when the dark mode setting is `manual`, the user's choice will be always kept on every visit (__i.e. no matter the browser is closed or not__).

Thanks and regards

**Comment by Pixinn** [comment]
It's working great. Thanks! 👍🏻
