### ISSUE TITLE
Gitment secret and TOC

### ISSUE THREAD

**Issue by iogbole** [jeffreytse/jekyll-theme-yat#16]
Hi @jeffreytse  and thanks for making this great theme. Is it possible to use GitHub secrets for the Gitment configuration instead of adding the client_secret  in the source code? https://github.com/jeffreytse/jekyll-theme-yat/blob/master/_config.yml#L135

Also, how can I disable TOC on the post pages? Many thanks

**Comment by jeffreytse** [comment]
Hi @iogbole 

About how to disable the TOC, you can see this issue #12.

Thanks and regards

**Comment by iogbole** [comment]
thanks
