### ISSUE TITLE
Option to disable code type badge?

### ISSUE THREAD

**Issue by mg979** [jeffreytse/jekyll-theme-yat#19]
To remove it, currently I have to copy the whole _sass directory and change _sass/yat/_base.scss, it's not ideal. Is there another way?

**Comment by jeffreytse** [comment]
Hi @mg979 

⛄ Currently, there is no option for disabling the badge of code, but I will extend it and add an option for this requirement. Welcome to star this project for further updates and features.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @mg979 

This feature has been supported and the latest gem version ([v1.7.0](https://rubygems.org/gems/jekyll-theme-yat/versions/1.7.0)) has been released.
👍 Welcome to update to the latest version. Thanks for your good help!

Thanks and regards.

**Comment by mg979** [comment]
Thanks works perfectly!
