### ISSUE TITLE
videos are not shown

### ISSUE THREAD

**Issue by pranavkrish04** [jeffreytse/jekyll-theme-yat#2]
## problem
I added a video to my blog and uploaded that to my Github page the Youtube video does not load. Although this works locally for me.
> this is the website: https://pranavkrish04.github.io/youtube/2020/08/30/video4.html

> markdown version of the page: https://github.com/pranavkrish04/pranavkrish04.github.io/blob/master/_posts/2020-07-28-introduction.md

**Comment by jeffreytse** [comment]
Hi @pranavkrish04 

If you want to make Jekyll site run as if it were local, such as let the custom plugins work properly, [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) could be very useful for you. 

Thanks and regards.

**Comment by pranavkrish04** [comment]
Thanks a lot for the response. The problem was solved as I used an embed this time. I was using a view link that was the reason.
Thanks again. { I also have responsiveness problems}

**Comment by pranavkrish04** [comment]
YUP ! added that and works like a gem. Really cool temoplate !!

**Comment by jeffreytse** [comment]
Hi @pranavkrish04 

The `jekyll-deploy-action` is really awesome and it could give you lots of awesome functions.
Hope you will like it and you could give a star tho the project if you like.

Thanks and regards.
