### ISSUE TITLE
"get_reading_time.html" is not support any languages

### ISSUE THREAD

**Issue by TaketoWakabayashi** [jeffreytse/jekyll-theme-yat#20]
Hi, @jeffreytse .
Thank you for your great theme.

I love your theme, and using for my Japanese blog with remote theme .
Then, I found the reading time is something wrong ...

I think {{ number_of_words }} liquid filter need "auto" or "cjk" option for Japanese.
https://github.com/jeffreytse/jekyll-theme-yat/blob/e3be95fe06ca57f7fa774e7b3d9efafe77cbb802/_includes/functions/get_reading_time.html#L12

But I can't fix this [issue by overriding in my local repos](https://jekyllrb.com/docs/themes/#overriding-theme-defaults).
I don't understand how work this theme completely, so please fix this issue, if it is easy.

**Comment by jeffreytse** [comment]
Hi @TaketoWakabayashi 

Thanks for your support. Now the issue has been addressed and settled down. And for better words counting, you can set the lang as below:

1. Setting the `lang` option for your whole site in `_config.yml`

```yml
# If you want to change site language, you can set lang option
lang: "jp"  # default lang is en
```

2. Setting the `lang` page metadata for your specific article

```md
---
layout: post
title: Welcome to Jekyll!
subheading: hello world!
categories: jekyll
tags: jekyll theme yat
sidebar: []
lang: jp
---
这是一段中文
これは日本の段落です
이것은 한국어 섹션입니다
This is a test
```

Thanks and regards

**Comment by TaketoWakabayashi** [comment]
@jeffreytse 
Thank you for fixing !
It seems to work correctly. ❤️ 

I'm sorry for the language-related issue again, `truncatewords: 50` doesn't seem to work well for Japanese too...
https://github.com/jeffreytse/jekyll-theme-yat/blob/48d4da4f1b0ee6d8a095fca301e6f3486a35f0b2/_includes/views/pagination.html#L31

I'd be happy if you have good solution for this issue. 🙏

**Comment by jeffreytse** [comment]
Hi @TaketoWakabayashi 

Thanks for your reporting and the latest commit ( 4be8ad5 ) has settled down this issue.

Thanks and regards

**Comment by TaketoWakabayashi** [comment]
Hi @jeffreytse 
It seems to work correctly too !

Thanks a lot !
I appreciate your kind response. ❤️
