### ISSUE TITLE
Unable to change the default heading and subheading

### ISSUE THREAD

**Issue by gkgaurav31** [jeffreytse/jekyll-theme-yat#28]
I was using minima theme and I am trying to switch to YAT. I am trying to change the default heading and subheading. 

I have tried this, but it didn't work:

defaults:
   home:
     heading: "my heading"
     subheading: "my subheading"
     banner: "Your image url"

It stays the same. 

How can I change it?

**Comment by gkgaurav31** [comment]
I solved it using this:

    scope:
      path: ""
    values:
      heading: "A blog for anyone..."
      subheading: "and everyone."

**Comment by xietx1995** [comment]
> I solved it using this:
> 
> ```
> scope:
>   path: ""
> values:
>   heading: "my heading"
>   subheading: "my subheading
> ```

You should change it in data file: `_data/defaults.yml`
