### ISSUE TITLE
bug on line breaking - not considering full works

### ISSUE THREAD

**Issue by hugopenna** [jeffreytse/jekyll-theme-yat#3]
Hey there,

I'm using your theme on my blog (hugopenna.com), and I saw that line breaks are not considering full words, I also looked on your demo site, and it has the same issue.

Here some examples: 

https://jeffreytse.github.io/jekyll-theme-yat/markdown/2018/12/05/an-exhibit-of-markdown.html
![image](https://user-images.githubusercontent.com/10089299/93898859-15f20f80-fcca-11ea-90a1-6d365303c5a9.png)

https://staging.hugopenna.com/devaneios/2020/09/22/empreender-nao-e-facil.html
![image](https://user-images.githubusercontent.com/10089299/93898953-2f935700-fcca-11ea-9e8b-9c4893d33d55.png)

Regards,
Hugo :)

**Comment by hugopenna** [comment]
You are really fast :D

**Comment by jeffreytse** [comment]
Hi @hugopenna 

This issue has been fixed and the latest gem version ([v1.5.4](https://rubygems.org/gems/jekyll-theme-yat/versions/1.5.4)) has been released.

👍 Welcome to update to the latest version. Thanks for your good help!

Thanks and regards.

**Comment by gsaltintas** [comment]
You can also change the attributes related to wrap and wordbreak in `_sass/yat/_layouts.scss` like the following.
```
    overflow-wrap: normal;
    word-wrap: normal;
    word-break: normal;
```
See all overflow option [here](https://css-tricks.com/almanac/properties/o/overflow-wrap/#:~:text=The%20overflow%2Dwrap%20property%20in,layout%20problems%20due%20to%20overflow.)

**Comment by jeffreytse** [comment]
Hi @gsaltintas 

Thanks for your information and the latest gem version ([v1.5.5](https://rubygems.org/gems/jekyll-theme-yat/versions/1.5.5)) has been released.

👍 Welcome to update to the latest version. Thanks for your good help!

Thanks and regards.
