### ISSUE TITLE
[BUG] Black header titles Dark Mode on mobile

### ISSUE THREAD

**Issue by CypherpunkSamurai** [jeffreytse/jekyll-theme-yat#38]
Hi, I tried this theme and the menu titles are unreadable in dark mode.

![](https://user-images.githubusercontent.com/66906402/118688933-242a0880-b824-11eb-9ae3-bba5980b854e.png)

![](https://user-images.githubusercontent.com/66906402/118689077-49b71200-b824-11eb-9295-5124b45c261b.png)

Also i would suggest please add another dark mode without #000000. It would suit the eyes better at night.

**Comment by jeffreytse** [comment]
Hi @CypherpunkSamurai 

Thanks for the reporting. Now this issue has been addressed and fixed, please update your code to the latest version.

Thanks and regards

**Comment by CypherpunkSamurai** [comment]
Thanks. That was a crazy fast commit. Thank you for dedicating your time to this issue :)
