### ISSUE TITLE
A night mode perhaps

### ISSUE THREAD

**Issue by dopewind** [jeffreytse/jekyll-theme-yat#4]
Just a suggestion

Basically what the title says, a dark mode and this will be perfect

Please do it if you have time

Cheers✌

**Comment by jeffreytse** [comment]
Hi @dopewind 

Thank you for your suggestion, actually, I'm planning the dark mode in future version. If you like this theme, welcome to star it  and the feature is coming.

Thanks and regards.

**Comment by dopewind** [comment]
Thanks a lot for responding @jeffreytse 

I have starred the project and I am looking forward to it, I am going forward with this theme, and when you add the dark mode I'll rebase it and publish

😀

**Comment by jeffreytse** [comment]
Hi @dopewind  

So happy to notice you that the __Night Mode__ has been supported with beautiful effects.
And the latest gem version ([v1.5.4](https://rubygems.org/gems/jekyll-theme-yat/versions/1.5.4)) has been released.

![Night Mode](https://user-images.githubusercontent.com/9413601/94983351-760f6e00-0574-11eb-9494-5303ad6228dc.gif)

👍 Welcome to update to the latest version. Thanks for your good help!

Thanks and regards.

**Comment by dopewind** [comment]
Thank you so much @jeffreytse 

That looks beautiful

**Comment by caolanxyz** [comment]
Hi, Just wondering how you would go about making it default to dark mode with the option to toggle to light mode?

**Comment by jeffreytse** [comment]
Hi @caolanxyz 

You can keep in the dark mode by setting the config option `night_mode: "on"` in file `_config.yml`.

Thanks and regards.
