### ISSUE TITLE
Request to improve chinese-font display in TOC

### ISSUE THREAD

**Issue by BadElement** [jeffreytse/jekyll-theme-yat#43]
![图片](https://user-images.githubusercontent.com/52056834/119421401-324ebc00-bd31-11eb-95e9-b2bb35c3a471.png)
![图片](https://user-images.githubusercontent.com/52056834/119421463-527e7b00-bd31-11eb-8644-f55a682dc2db.png)

显示出的看着不舒服啊
Showing it is uncomfortable

**Comment by BadElement** [comment]
第二个还好，其实还顺眼
但是第一个就很不舒服，粗细不一样啊
The second is ok, it is actually pleasing to the eye.
But the first one is very uncomfortable, the thick is different.

如果可以得到改进
那真是不胜感激
If you can improve
That is really grateful

**Comment by jeffreytse** [comment]
Hi @BadElement 

Are you talking about the font weight of TOC items? Some characters are bold as the heading in the article?

Thanks and regards

**Comment by BadElement** [comment]
不是字体大小的问题
是TOC中字体的显示问题
有的粗有的细
![图片](https://user-images.githubusercontent.com/52056834/119429781-25869400-bd42-11eb-870e-fa7f453ca931.png)

但是在文章中就没有这个问题

**Comment by jeffreytse** [comment]
Hi, @BadElement 

Accordingly, it's the font family issue, could you provide me a page link to have a checking further?

Thanks and regards

**Comment by BadElement** [comment]
好的:
OK:
https://badelement.vercel.app/done/2021/05/25/SHIT-1.html


> 
> 
> Hi, @BadElement
> 
> Accordingly, it's the font family issue, could you provide me a page link to have a checking further?
> 
> Thanks and regards

**Comment by jeffreytse** [comment]
Hi @BadElement 

There is no problem in my enviroment, so I think it is the issue your system has no the corresponding font family.

![image](https://user-images.githubusercontent.com/9413601/119464726-9bf0b980-bd75-11eb-88e4-be88ea5e9540.png)

You can change the default font family by yourself in the `_sass/yat.scss` file.

Thanks and regards

**Comment by BadElement** [comment]
正常了
感谢

Display is normal
thank you

> _sass\yat.scss ：
> $base-font-family: "Microsoft YaHei"

**Comment by jeffreytse** [comment]
Hi @BadElement 

Now the commit (de8c813aea0c96733c14de26305b3ad91a31ad80) has updated the default font family for better experience of the text display. If you have no more request, don't forget to close this issue.

Thanks and regards
