### ISSUE TITLE
Request repair page scrolling bug in categories.html

### ISSUE THREAD

**Issue by BadElement** [jeffreytse/jekyll-theme-yat#44]
这是错误页面：
this is error page:

![图片](https://user-images.githubusercontent.com/52056834/119523784-9e700500-bdaf-11eb-9384-42cb69034598.png)
https://badelement.github.io/categories.html

我发现中文的分类并不会随着点击而滚动
而英文的分类就可以
I found that Chinese text will not scroll when I clicked text
But the English text can do that

**Comment by jeffreytse** [comment]
Hi @BadElement 

This issue has been addressed and settled down. Please update your theme to the latest version.

Thanks and regards
