### ISSUE TITLE
A nonexistent file in  _config.yml

### ISSUE THREAD

**Issue by BadElement** [jeffreytse/jekyll-theme-yat#45]
![图片](https://user-images.githubusercontent.com/52056834/120071214-d2556e00-c0c0-11eb-9449-558d98e250c7.png)

我没有在仓库里找到这个文件
I didn't find this file(about.md) in the dir.

**Comment by jeffreytse** [comment]
Hi @BadElement 

It's the `about.html` now, and that's just an example for you to config the header menu items.

Thanks and regards
