### ISSUE TITLE
Weird behavior with the sample

### ISSUE THREAD

**Issue by Igortorrente** [jeffreytse/jekyll-theme-yat#51]
First of all, Thanks for this incredible theme.
Second, I'm not sure if this is a problem of the theme or the Jekyll

For some reason, the sample below produces a wrong result. Does anyone have any idea of what could be?

~~~
---
layout: post
title: testtttt
subtitle: just a test.
categories: test
tags: [test, bug, weird, help]
---
``` diff
+        'user_exists' => 'SELECT EXISTS(SELECT 1 FROM table WHERE username = (:username || \'@sample'))',
+        'get_users' => 'SELECT split_part(username, \'@\', 1) FROM table WHERE (username ILIKE :search) OR (name ILIKE :search)',
+        'get_password_hash_for_user' => 'SELECT split_part(password, \'{CRYPT}\', 2) FROM table WHERE username = (:username || \'@sample\')',
+        'set_password_hash_for_user' => 'UPDATE table SET password =  \'{CRYPT}\' || :new_password_hash WHERE username = (:username || \'@sample\')',
``` 
Reload the Nginx:

``` console
$ sudo nginx -s reload
```

#### Sample title three

Sample test wit a [sample link](https://google.com).

The \<password\> will be in the file `samplefile.tips` in the `sample:` section.

| **Sample table**               | **Sample table**    |
| ---------------------------------- | -------------------------------------- |
| Email user: joanadarc@sample.com | Email user: joanadarc@sample.com     |
| Nextcloud user: joanadarc          | Nextcloud user: joanadarc@sample.com |
~~~

![Screenshot_2021-07-26 testtttt](https://user-images.githubusercontent.com/18224386/127084419-1d09cee0-b2db-4cb7-ac58-4e97ddb7f1f7.png)

**Comment by jeffreytse** [comment]
Hi @Igortorrente,

Firstly, thanks for your good issue and support to this theme. And I will take a look your issue as soon as possible, could you disable the plugin `jekyll-spaceship` and try again, I think it should be the plugin issue. Welcome to  star this project for further updates in the future. : )

Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @Igortorrente,

This issue has been created (jeffreytse/jekyll-spaceship#58) and settled down, please update your gem to the GitHub master version, here is the code snippet for your reference, just put this snippet to your `Gemfile`:

```ruby
gem 'jekyll-spaceship', git: 'https://github.com/jeffreytse/jekyll-spaceship'
```

Thanks and Regards

**Comment by Igortorrente** [comment]
Wow, this was quicky and solved the issue, thanks!!!!!!!!!!!!

**Comment by dukechain2333** [comment]
Hi!
I was using Github Actions to publish my pages and also added the following snippet to my Gemfile. However, Mermaid still not working properly.
```
gem 'jekyll-spaceship', git: 'https://github.com/jeffreytse/jekyll-spaceship'
```
And this is what my pages look like.
![image](https://user-images.githubusercontent.com/57356723/193447847-e7c68037-8682-42d0-8239-5cd20efdb9e0.png)

And my Gemfile looks like this
![image](https://user-images.githubusercontent.com/57356723/193447890-55bb4080-31ea-4a29-b778-071226035d86.png)


@jeffreytse

**Comment by jeffreytse** [comment]
Hi @dukechain2333 

It's your configuration isn't correct, you can check the README of [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) step by step, and please ensure that you have `gh-pages` branch in your repo.

Thanks & Regards

**Comment by dukechain2333** [comment]
> 

Problem Solved. Thank you.
