### ISSUE TITLE
TOC being auto "translated" to English

### ISSUE THREAD

**Issue by jtmullen** [jeffreytse/jekyll-theme-yat#55]
I noticed this issue locally and noticed it also [appears on your blog](https://jeffreytse.net/about.html), so it must not be just a me issue. 

Google translate is detecting TOC (the abbreviation for table of contents) as a Romanian word and translating it to english: 
![image](https://user-images.githubusercontent.com/30645732/129115613-29b5f0be-921f-428f-aaa0-906aef4cedcf.png)

You can replicate this on Google Translate: https://translate.google.com/?sl=auto&tl=en&text=TOC&op=translate

This is also resulting in TOC translating to "heel" in other languages too. This didn't originally stick out to me as much as the english getting translated - but in retrospect it makes sense it would be wrong in all languages. 

I've just taken a cursory look at how this google translate works - I _think_ the method you are using supports passing in what language the site is written in, instead of using auto-detect. That should fix this issue, trying it with google translate if you give it "TOC" and say that it is english it won't translate it since it is not a word. 

Of course I'm not sure if there are any YAT users that rely on the auto-detect for language for some reason which could complicate this. 

Thanks!

**Comment by jtmullen** [comment]
Just tried this out since it was an easy change to hardcode: 

https://github.com/jtmullen/jekyll-theme-yat/blob/1e4c9d46be52ea461cc9d89cd0ca8a0fd601f581/_includes/extensions/google-translate.html#L27

Seemed to work _most_ of the time. Once in a while when switching back to English it would change it to "heel" seemingly ignoring the site language. But I never saw it wrong in other languages, and clicking english again changed it back to TOC. 

Alternatively, adding the class "notranslate" prevents it from being translated. For TOC specifically (or anything else that doesn't make sense to translate since it is not a word) this works as a fix too. Specifically for this issue: 
https://github.com/jtmullen/jekyll-theme-yat/blob/4c1504891421ba26de6295462b5cf21590ad588c/_includes/sidebar/article-menu.html#L10

**Comment by jeffreytse** [comment]
Hi @jtmullen 

Thanks a lot for the suggestion, I will follow up this issue as soon as possible.

Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @jtmullen

This issue has been settled down. Hope you have a good  day! : D

Thanks and Regards
