### ISSUE TITLE
github-action error

### ISSUE THREAD

**Issue by europani** [jeffreytse/jekyll-theme-yat#56]
Hello.. Thank you for ur awesome theme...
I have a problem while hosting my post...
I pushed my commit but github-action failed..
Can you help me??

![image](https://user-images.githubusercontent.com/48157259/129693898-5258ba30-56b4-4067-80ea-567e6eb849d2.png)

![image](https://user-images.githubusercontent.com/48157259/129694194-91e09e1f-0de8-4860-b457-0d47622e499e.png)

**Comment by jeffreytse** [comment]
Hi @europani 

Do you still get this issue now?

Thanks and Regards

**Comment by europani** [comment]
It was failed... but suddenly it's showing SUCCESS!!!
Did you do something for me??

**Comment by jeffreytse** [comment]
Hi @europani ,

This issue is related to jeffreytse/jekyll-deploy-action#25.

Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @europani ,

Now this issue has been fixed completely, the details you can check the issue mentioned above.

Thanks and Regards

**Comment by europani** [comment]
It worked well!!
thank you so much @jeffreytse

**Comment by jeffreytse** [comment]
@europani  Good to hear that, welcome to star this project for further updates in the future. Hope you have a good day! : )
