### ISSUE TITLE
how to delete the code related to translation?

### ISSUE THREAD

**Issue by xietx1995** [jeffreytse/jekyll-theme-yat#58]
Hey, YAT is really great! The translation is also great. But my friends can't access URLs that belong to Google. So when they visit my site, the browser will be stuck at fetching the files related to translation. How can I delete the code related to translation?

**Comment by jeffreytse** [comment]
Hi @xietx1995 

To disable the Google Translation function, you should set the option `translate_langs` of `_config.yml` to an empty array, below is the code snippet.

```yml
# Translate languges
translate_langs: []
``` 

Thanks and Regards

**Comment by xietx1995** [comment]
> Hi @xietx1995
> 
> To disable the Google Translation function, you should set the option `translate_langs` of `_config.yml` to an empty array, below is the code snippet:
> 
> ```yaml
> # Translate languges
> translate_langs: []
> ```
> 
> Thanks and Regards

Thanks, I deleted the translate languages in the data file `_data/translate_langs.yml`. It works.

**Comment by jeffreytse** [comment]
@xietx1995  Sure, it's another way for you to reach out. Glad to hear that you have settled down.
