### ISSUE TITLE
How to modify the icon of a webpage ?

### ISSUE THREAD

**Issue by vanhiupun** [jeffreytse/jekyll-theme-yat#64]
Hi! I want to know how to change the icon of the website. I have been looking for a long time and I have no idea. Please tell me the specific method. Thank you so much!
![1635751592(1)](https://user-images.githubusercontent.com/89436345/139636742-0e7346b2-6ff9-4de1-a3cc-9460c9e39dc8.jpg)

**Comment by jeffreytse** [comment]
Hi @vanhiupun 

You should use [the favicon option](https://github.com/jeffreytse/jekyll-theme-yat/blob/ac3833777c63ae6bc66c59275a2c6dccef16b762/_config.yml#L52) in the `_config.yml`

Thanks and Regards

**Comment by vanhiupun** [comment]
Hello, during the process of creating my website, I found a problem. After I click into the article, my website icon is not displayed. Is this a problem with my misconfiguration?
![image](https://user-images.githubusercontent.com/89436345/142826067-0ed6d917-c343-4d75-bbc5-2a000de5e9fd.png)

**Comment by jeffreytse** [comment]
Hi @vanhiupun 

For the favicon resources, please use absolute path, do not use a relative path such as `foo/bar/baz.ico` or `./foo/bar/baz.ico`.

Thanks and Regards

**Comment by vanhiupun** [comment]
@jeffreytse 
This problem has been resolved. thank you very much!
