### ISSUE TITLE
How to modify the style of the navigation bar

### ISSUE THREAD

**Issue by vanhiupun** [jeffreytse/jekyll-theme-yat#66]
Hi!  @jeffreytse

I want to modify the style of the navigation bar, what should I do

1. Change `text` to `icon`
2. Add an `icon` to link it to my `GitHub repository`

Looking forward to your reply

**Comment by MohammadSanadAlTaher** [comment]
Hi, 

Did you find a solution?
Also, I have gutted the theme and am rebuilding a custom theme. Been trying to adjust the transition speed upon clicking on the nav menu. Any clue how to do that?

Thanks.
