### ISSUE TITLE
Modify the menu bar style

### ISSUE THREAD

**Issue by vanhiupun** [jeffreytse/jekyll-theme-yat#67]
Hi! @jeffreytse

I add icon behind the menu bar to link to the warehouse
Something like this

![QQ20211126-222525](https://user-images.githubusercontent.com/89436345/143596438-790ec240-5ad1-4e7f-8bf5-5a62a13bde1d.png)

Now I want to change the menu bar to this type.
<https://docs.docker.com/>
Can you tell me how to modify it?

Looking forward to your reply, thank you very much!

**Comment by jeffreytse** [comment]
Hi @vanhiupun 

Thanks for your issue, sorry for the late reply, recently I'm quite busy. If you want this kind of head style, you should modify the css style under the `_sass` folder.

Thanks and Regards

**Comment by vanhiupun** [comment]
Hi!@jeffreytse 
Thank you for your reply, I will look into it
