### ISSUE TITLE
build_and_deploy github issue

### ISSUE THREAD

**Issue by MbMa** [jeffreytse/jekyll-theme-yat#7]
Hi,

First thanks for your amazing work on this theme.

The issue I encounter is when deploying in github pages I recieve an error in the build_and_deploy Actions tab of github : 

`Run jeffreytse/jekyll-deploy-action@master
/usr/bin/docker run --name aac2aab594691e412e4bc1afc032c08ff3f133_cb0007 --label aac2aa --workdir /github/workspace --rm -e INPUT_PROVIDER -e INPUT_TOKEN -e INPUT_REPOSITORY -e INPUT_BRANCH -e INPUT_JEKYLL_SRC -e INPUT_JEKYLL_CFG -e INPUT_JEKYLL_BASEURL -e INPUT_CNAME -e INPUT_ACTOR -e INPUT_BUNDLER_VER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mbarki/mbarki":"/github/workspace" aac2aa:b594691e412e4bc1afc032c08ff3f133`

Do you have an idea how to fix it ? 

Many thanks

**Comment by jeffreytse** [comment]
Hi @MbMa 

I think you can check the [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) usage first, maybe some steps you haven't done.

Thanks and regards.

**Comment by MbMa** [comment]
Thanks @jeffreytse . This solved my issue.

**Comment by jeffreytse** [comment]
Hi @MbMa 

😃 So happy to help you settle your problem. If you like this theme, you can give __a little star__ to it for future updates.

Thanks and regards.

**Comment by MbMa** [comment]
sure ! it's done.
