### ISSUE TITLE
Some troubles with self-hosted jekyll

### ISSUE THREAD

**Issue by giuliomagnifico** [jeffreytse/jekyll-theme-yat#72]
Hi, Im build my site on my VPS with your (beautiful, thanks) theme, but I'm having some troubles with the baseurl in config.yml.

``` 
baseurl: "" 
url: "http://giuliomagnifico.blog" 
```

Now is empty and my site is correct, but your theme doesn't load some resources like images/banner. I think the theme works fine when used on GitHub pages with the baseurl path but it has some troubles when it has the baseurl path empty, or something similar. I can't figure out what is wrong:

```Auto-regeneration: enabled for '/home/etcetera'
Server address: http://12345:4000/etcetera/
Server running... press ctrl-c to stop.
[2022-01-11 08:28:31] ERROR `/etcetera/default' not found.
[2022-01-11 08:28:31] ERROR `/etcetera/default' not found.
[2022-01-11 08:28:34] ERROR `/etcetera/default' not found.
[2022-01-11 08:28:36] ERROR `/etcetera/categories.html' not found.
[2022-01-11 08:28:36] ERROR `/etcetera/categories.html' not found.
```
Thanks for your help.

**Comment by jeffreytse** [comment]
Hi @giuliomagnifico 

Please check your baseurl, I think you have a wrong baseurl.

Thanks and Regards

**Comment by giuliomagnifico** [comment]
Thanks for the reply @jeffreytse,the trouble was with the the installation method with gem, it wasn't loading correctly some resources, I've manually put all of your theme files in my VPS and now works perfectly. Is working without the baseurl, it's empty but it's correct for my installation.

**Comment by giuliomagnifico** [comment]
I'm also having troubles with the order of the categories, using the config.yml nothing is changing after I modified the layout. Is there another way to change the order of the pages/menu?

![Screen Shot 2022-01-12 at 09 49 13](https://user-images.githubusercontent.com/1975176/149094844-5cea7c2e-e439-41ec-bcf4-a3f9bcf8933f.jpeg)

**Comment by jeffreytse** [comment]
@giuliomagnifico The category items should have indentation according to the yml format.

**Comment by giuliomagnifico** [comment]
> @giuliomagnifico The category items should have **indentation** according to the yml format.

Damn thanks, what a mistake sorry, this solved my trouble.

**Comment by jeffreytse** [comment]
@giuliomagnifico You're welcome, hope you have a good day! : )
