### ISSUE TITLE
Posts not being loaded by [MathjaxProcessor]

### ISSUE THREAD

**Issue by alvarovaca** [jeffreytse/jekyll-theme-yat#8]
I have the following posts in my **_posts/** folder:

```
-rw-r--r-- 1 alvaro alvaro 43783 oct  9 12:29 2020-10-01-configuracion-raid-5.markdown
-rw-r--r-- 1 alvaro alvaro 33636 oct  9 12:28 2020-10-02-almacenamiento-con-rclone.markdown
-rw-r--r-- 1 alvaro alvaro 25568 oct 17 20:15 2020-10-03-instalacion-debian-10.markdown
-rw-r--r-- 1 alvaro alvaro 73700 oct 17 11:39 2020-10-10-servidor-dhcp-con-nat.markdown
-rw-r--r-- 1 alvaro alvaro 38531 oct 15 13:50 2020-10-11-cifrado-asimetrico-gpg-openssl.markdown
-rw-r--r-- 1 alvaro alvaro 39324 oct 17 20:18 2020-10-17-instalacion-automatica-pxe.markdown
-rw-r--r-- 1 alvaro alvaro 21051 oct 17 19:07 2020-10-17-virtualhosting-con-apache.markdown
```

So when I run the `bundle exec jekyll serve` command, the output from Jekyll Spaceship only shows that it has processed 4 of them all (the first 3 posts are not shown up):

```
  Jekyll Spaceship: [MathjaxProcessor] _posts/2020-10-10-servidor-dhcp-con-nat.markdown
  Jekyll Spaceship: [MathjaxProcessor] _posts/2020-10-11-cifrado-asimetrico-gpg-openssl.markdown
  Jekyll Spaceship: [MathjaxProcessor] _posts/2020-10-17-instalacion-automatica-pxe.markdown
  Jekyll Spaceship: [MathjaxProcessor] _posts/2020-10-17-virtualhosting-con-apache.markdown
```

Anyways, although they are not being shown, they are still accessible in the generated site. This is really not an important issue, but it has drawn my attention that 3 of my posts are not being processed by MathjaxProcessor but still accessible in the final generated site.

[Here](https://github.com/alvarovaca/blog-alvarovf) you have my GitHub repository with the website code, in case you need it. Thanks.

**Comment by jeffreytse** [comment]
Hi @alvarovaca 

Thanks for your report and the [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship) plugin will auto handle the files that contain mathjax math expression, so I think the files that was not being shown are not contain any mathjax expression, the detail you can take a look [here](https://github.com/jeffreytse/jekyll-spaceship#2-mathjax-usage).

Thanks and regards.

**Comment by alvarovaca** [comment]
@jeffreytse That's strange, since I have been looking deeply in the code and I can't find any math expression that should use MathJax for processing.

**Comment by jeffreytse** [comment]
Hi @alvarovaca 

Yes, it's really strange, could you open a new issue about this problem in the [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship), I will update there if I addressed the problem.

Thanks and regards.
